export const PROVIDER_META: Record<string, { label: string; icon: string }> = {
  adn:         { label: 'ADN',         icon: 'assets/icons/providers/ad.png' },
  appletv:     { label: 'Apple TV+',   icon: 'assets/icons/providers/apple.png' },
  canal:       { label: 'Canal+',      icon: 'assets/icons/providers/canal.jpg' },
  crunchyroll: { label: 'Crunchyroll', icon: 'assets/icons/providers/crunchyroll.png' },
  disney:      { label: 'Disney+',     icon: 'assets/icons/providers/disney.png' },
  francetv:    { label: 'France TV',   icon: 'assets/icons/providers/francetv.webp' },
  hbo:         { label: 'HBO',         icon: 'assets/icons/providers/hbo.jpg' },
  m6:          { label: 'M6+',         icon: 'assets/icons/providers/m6.svg' },
  netflix:     { label: 'Netflix',     icon: 'assets/icons/providers/netflix.png' },
  primevideo:  { label: 'Prime Video', icon: 'assets/icons/providers/primevideo.png' },
  molotov:     { label: 'Molotov',     icon: 'assets/icons/providers/molotov.png' },
  paramount:   { label: 'Paramount',   icon: 'assets/icons/providers/paramount.png' },
  tf1:         { label: 'TF1',         icon: 'assets/icons/providers/tf1.webp' },
  viki:        { label: 'Viki',        icon: 'assets/icons/providers/viki.png' },
  warner:      { label: 'Warner TV',   icon: 'assets/icons/providers/warner.png' },
  youtube:     { label: 'Youtube',     icon: 'assets/icons/providers/youtube.jpeg' },
  generic:     { label: 'Autre',       icon: 'assets/icons/providers/generic.png' },
};
